DROP TABLE IF EXISTS {{SCHEMA}}.Team;
GO

CREATE TABLE {{SCHEMA}}.Team (
    TeamId INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL,
    TeamName NVARCHAR(50) NOT NULL,

    CONSTRAINT FK_Team_User
        FOREIGN KEY (UserId)
        REFERENCES {{SCHEMA}}.[User](UserId)
);
GO
