DROP TABLE IF EXISTS pokemon.[User];
GO

CREATE TABLE pokemon.[User] (
    UserId INT IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(50) NOT NULL UNIQUE,
    Wins INT NOT NULL DEFAULT 0,
    Losses INT NOT NULL DEFAULT 0
);
GO
